use [Novateca.Web];

select * from Book;

insert into Book(
   [TitleMain],[Subtitle],[AuthorMain],[Authors],[Edition],[PlaceOfPublication],[PublishingCompany],
   [YearOfPublication],[TotalPages],[BookSubject],[Abstract],[ISBN],[URLImage],[URLEbook]
) values
('Quem é você Alasca?','','GREEN, John','GREEN, John','1º','São Paulo, SP - Brasil','Intrínseca','2010','240','Romance Juvenil','Miles Halter é um adolescente que leva uma vida sem graça e sem muitas emoções na Flórida. Ele tem um gosto peculiar: memorizar as últimas palavras de grandes personalidades da história. E uma dessas personalidades: François Rabelais, um escritor do século.','9788578273422','/images/capas/livros/alasca.jpg',''),
('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','9788575222494','/images/capas/livros/aspnet.jpg',''),
('Contabilidade Pública','Integrando União, Estados e Municípios','LIMA, Diana Vaz de','LIMA, Diana Vaz de; CASTRO, Róbison Gonçalves de','3º','São Paulo, SP - Brasil','Atlas','2007','234','Contabilidade','Este livro contempla as principais ferramentas da Contabilidade Pública, oferecendo aos profissionais e estudantes da área, as informações técnicas necessárias para o exercício profissional, o ingresso no serviço público e a formação acadêmica.','9788522447091','/images/capas/livros/contabilidade.jpg','');
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/contabilidade.jpg',''),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/cujo.jpg',''),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/direito.jpg',''),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/irresistivel.jpg',''),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/medicina.jpg',''),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/milho.jpg',''),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/poderoso.jpg','');
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/potter.jpg','');

insert into Multimedia(
	[TitleMain],[DGM],[Subtitle],[Director],[PlaceOfPublication],[PublishingCompany],[YearOfPublication]
    ,[PhysicalDescription],[MultimediaSubject],[Abstract],[NoteOfParticipants],[TargetAudience],[Language]
    ,[URLImage]
) values
('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/agente.jpg'),
('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/contrabando.jpg'),
('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/eclipse.jpg');
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/hospedeira.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/jovens.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/malevola.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/premonicao.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/resident.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/sabotagem.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/um.jpg');

insert into Newspaper(
	   [TitleMain],[Subtitle],[Edition],[PlaceOfPublication],[PublishingCompany],[NewspaperSubject]
      ,[CurrentPeriodicity],[ISSN],[URLImage]
) values
('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/caras.jpg'),
('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/claudia.jpg'),
('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/embarque.jpg');
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/empresa.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/epoca.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/nerd.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/rural.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/veja.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/viagem.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/voce.jpg');
