use [Novateca.Web];

select * from Book;

insert into Book(
   [TitleMain],[Subtitle],[AuthorMain],[Authors],[Edition],[PlaceOfPublication],[PublishingCompany],
   [YearOfPublication],[TotalPages],[BookSubject],[Abstract],[ISBN],[URLImage],[URLEbook]
) values
('Quem é você Alasca?','','GREEN, John','GREEN, John','1º','São Paulo, SP - Brasil','Intrínseca','2010','240','Romance Juvenil','Miles Halter é um adolescente que leva uma vida sem graça e sem muitas emoções na Flórida. Ele tem um gosto peculiar: memorizar as últimas palavras de grandes personalidades da história. E uma dessas personalidades: François Rabelais, um escritor do século.','9788578273422','/images/capas/livros/alasca.jpg',''),
('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','9788575222494','/images/capas/livros/aspnet.jpg',''),
('Contabilidade Pública','Integrando União, Estados e Municípios','LIMA, Diana Vaz de','LIMA, Diana Vaz de; CASTRO, Róbison Gonçalves de','3º','São Paulo, SP - Brasil','Atlas','2007','234','Contabilidade','Este livro contempla as principais ferramentas da Contabilidade Pública, oferecendo aos profissionais e estudantes da área, as informações técnicas necessárias para o exercício profissional, o ingresso no serviço público e a formação acadêmica.','9788522447091','/images/capas/livros/contabilidade.jpg','');
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/contabilidade.jpg',''),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/cujo.jpg',''),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/direito.jpg',''),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/irresistivel.jpg',''),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/medicina.jpg',''),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/milho.jpg',''),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/poderoso.jpg','');
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','/images/capas/livros/potter.jpg','');

insert into Multimedia(
	[TitleMain],[DGM],[Subtitle],[Director],[PlaceOfPublication],[PublishingCompany],[YearOfPublication]
    ,[PhysicalDescription],[MultimediaSubject],[Abstract],[NoteOfParticipants],[TargetAudience],[Language]
    ,[URLImage]
) values
('Agente H','[gravação de video]','Missão resgate','Kathrine Windfeld','Suécia','PlayArte','2012','DVD','Ação','Agente Especial Carl Hamilton entrou é enviado em uma missão nos bastidores da máfia russa, para desmembrar a empresa, que planeja vender armas a grupos terroristas. No entanto, no meio da operação, um grupo de homens fortemente armados veio e matou todos os presentes, em adição a Hamilton, levando armas. Quem são essas pessoas? Quem é que eles funcionam? Em busca de respostas, o agente começa a persegui-los em todo o mundo, seguindo pistas que vão levar você a acreditar que esta é uma conspiração internacional real.','Aleksandr Nosik, Alexandra Alegren, Anders Ahlbom, Anna Lindmarker, Ashraf Farah, Bassam Touma, Cedric Proust, Dan Ekborg, David Dencik, Duncan Bruining (...)','16','Português-BR','/images/capas/multimidias/agente.jpg'),
('Contrabando','[gravação de video]','','Baltasar Kormákur','EUA','Relativity Media, Working Title Films','2012','Blu-Ray','Ação, Drama, Thriller','Um thriller galopante sobre um homem que tenta deixar para trás o mundo do crime, e considera a sua família, fazendo tudo para a proteger. Tendo Nova Orleães como cenário, o filme explora o sombrio e perigoso mundo do contrabando internacional, cheio de criminosos desesperados e polícias corruptos, altas apostas e grandes pagamentos, onde a lealdade raramente existe e a morte está ao virar da esquina. Há muito que Chris Farraday (Wahlberg) deixou a vida do crime, mas depois do seu cunhado Andy (Caleb Landry Jones) estragar um negócio de droga ao seu cruel patrão, Tim Briggs (Giovanni Ribisi), Chris vê-se obrigado a voltar a fazer aquilo que ele faz de melhor – contrabando – para pagar a dívida de Andy. Chris é um lendário contrabandista e rapidamente forma uma equipa com a ajuda do seu melhor amigo Sebastian (Ben Foster), para um golpe final no Panamá, na esperança de trazer milhões de notas falsas.','Mark Wahlberg, Kate Beckinsale, Ben Foster, Giovanni Ribisi','16','Inglês','/images/capas/multimidias/contrabando.jpg'),
('A Saga Crepúsculo','[gravação de vídeo]','Eclipse','David Slade','EUA','Temple Hill Entertainment','2010','DVD','Fantasia, Romance','Enquanto Seattle é devastada por uma sequência de mortes misteriosas, um malicioso vampiro continua a sua busca por vingança. Bella novamente se encontra rodeada por perigo. Em meio a tudo isso, ela é forçada a escolher entre seu amor por Edward e sua amizade com Jacob – sabendo que sua decisão tem o potencial para inflamar a luta entre vampiros e lobisomens. Com sua graduação aproximando rapidamente, Bella tem mais uma decisão para fazer: vida ou morte.','Kristen Stewart, Robert Pattinson, Taylor Lautner','14','Português-BR','/images/capas/multimidias/eclipse.jpg');
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/hospedeira.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/jovens.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/malevola.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/premonicao.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/resident.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/sabotagem.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','656','Informática','Esta segunda edição do livro foi revisada e atualizada para a versão 4.0 e apresenta muitos exemplos,códigos, tutoriais, dicas, truques e conceitos relacionados a aspectos básicos e avançados do C# 4.0 e aos principais recursos do ASP.NET 4.0.','978-85-7522-249-4','','/images/capas/multimidias/um.jpg');

insert into Newspaper(
	   [TitleMain],[Subtitle],[Edition],[PlaceOfPublication],[PublishingCompany],[NewspaperSubject]
      ,[CurrentPeriodicity],[ISSN],[URLImage]
) values
('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/caras.jpg'),
('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/claudia.jpg'),
('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/embarque.jpg');
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/empresa.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/epoca.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/nerd.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/rural.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/veja.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/viagem.jpg'),
--('Como programar com asp.net e C#','','LOTAR, Alfredo','LOTAR, Alfredo','2º','São Paulo, SP - Brasil','Novatec Editora Ltda','2010','/images/capas/periodicos/voce.jpg');
